---
- hosts: all
  remote_user: vagrant
  vars:
    download_folder: /opt
    java_download_url: http://download.oracle.com/otn-pub/java/jdk/8u144-b01/090f390dda5b47b9b721c7dfaa008135/jdk-8u144-linux-x64.tar.gz
    java_name: "{{download_folder}}/jdk1.8.0_144"
    java_archive: "{{download_folder}}/jdk-8u144-linux-x64.tar.gz"
    maven_download_url: http://ftp.jaist.ac.jp/pub/apache/maven/maven-3/3.5.0/binaries/apache-maven-3.5.0-bin.tar.gz
    maven_name: "{{download_folder}}/apache-maven-3.5.0"
    maven_archive: "{{download_folder}}/apache-maven-3.5.0-bin.tar.gz"

  tasks:
  - name: install general packages
    yum: name={{ item }} state=latest
    become: true
    with_items:
      - vim
      - git
      - wget
      - firefox

  - name: add environments to bash_profile
    lineinfile:
      path: "~/.bash_profile"
      state: present
      line: "{{item}}"
    with_items:
      - "export JAVA_HOME={{java_name}}"
      - "export M3_HOME={{maven_name}}"
      - "export PATH=$PATH:M3_HOME/bin"

  - name: check java exists
    stat: path={{java_name}}
    register: java_exists

  - block:
    - name: Download Java
      command: "wget -q -O {{java_archive}} --no-check-certificate --no-cookies --header 'Cookie: oraclelicense=accept-securebackup-cookie' {{java_download_url}} creates={{java_archive}}"

    - name: Unpack archive
      command: "tar -zxf {{java_archive}} -C {{download_folder}} creates={{java_name}}"

    - name: Fix ownership
      file: state=directory path={{java_name}} owner=root group=root recurse=yes

    - name: Make Java available for system
      command: 'alternatives --install "/usr/bin/java" "java" "{{java_name}}/bin/java" 2000'

    - name: Clean up
      file: state=absent path={{java_archive}}
    become: true
    when: not java_exists.stat.exists

  - name: check maven exists
    stat: path={{maven_name}}
    register: maven_exists

  - block:
    - name: download and unarchive maven
      unarchive: 
        src: "{{maven_download_url}}"
        dest: "/opt"
        remote_src: True

    - name: Fix ownership
      file: state=directory path={{maven_name}} owner=root group=root recurse=yes

    - name: Clean up
      file: state=absent path={{maven_archive}}
    become: true
    when: not maven_exists.stat.exists
